import TableDataStyle from "../../js/enum/tableDataStyle";

export default {
	data() {
		return {
			WAREHOUSE_TABLE: {
				InwardOutwardListTitle: "Nhập, xuất kho",
				InwardOutwardList: [
					{
						name: "Ngày hạch toán",
						field: "mathematics_date",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Số chứng từ",
						field: "voucher_code",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
						color: TableDataStyle.COLOR.Blue,
					},
					{
						name: "Diễn giải",
						field: "description",
						width: "400px",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Tổng tiền",
						field: "total_price",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Right,
					},
					{
						name: "Người giao/Người nhận",
						field: "contact_name",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Đã lập CT bán hàng",
						field: "is_mention",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Ngày chứng từ",
						field: "voucher_date",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
						color: TableDataStyle.COLOR.AllGreen,
					},
					{
						name: "Loại chứng từ",
						field: "voucher_type",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Ngày tạo",
						field: "created_date",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Người tạo",
						field: "created_by",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Ngày chỉnh sửa",
						field: "modified_date",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
					{
						name: "Người chỉnh sửa",
						field: "modified_by",
						type: TableDataStyle.TYPE.Text,
						pos: TableDataStyle.POS.Left,
					},
				],
				InWardDetail: {
					TABLE_INPUT: [
						{
							name: "Mã hàng",
							field: "commodity_code",
							width: "150px",
							type: TableDataStyle.TYPE.Combobox,
							pos: TableDataStyle.POS.Left,
							api: this.$api.COMMODITY.Api,
							style: this.$api.COMMODITY.Style,
							vmodel: "commodity_id",
							controller: "Commoditys",
							form: 'showWarehouseAddCommodity',
							enable: true,
						},
						{
							name: "Tên hàng",
							field: "commodity_name",
							width: "300px",
							type: TableDataStyle.TYPE.Input,
							pos: TableDataStyle.POS.Left,
							enable: true,
						},
						{
							name: "Kho",
							field: "warehouse_code",
							width: "150px",
							type: TableDataStyle.TYPE.Combobox,
							pos: TableDataStyle.POS.Left,
							api: this.$api.WAREHOUSE.Api,
							style: this.$api.WAREHOUSE.Style,
							vmodel: "warehouse_id",
							controller: "Warehouses",
							form: 'showWarehouseAdd',
							enable: true,
						},
						{
							name: "TK nợ",
							field: "credit_account_number",
							width: "150px",
							type: TableDataStyle.TYPE.ComboboxNotAdd,
							api: this.$api.DEBIT_ACCOUNT.Api,
							style: this.$api.DEBIT_ACCOUNT.Style,
							vmodel: "debit_account_id",
							subfield: "account_id",
							controller: "Accounts",
							pos: TableDataStyle.POS.Left,
							enable: true,
						},
						{
							name: "TK có",
							field: "debit_account_number",
							width: "150px",
							type: TableDataStyle.TYPE.ComboboxNotAdd,
							pos: TableDataStyle.POS.Left,
							api: this.$api.CREDIT_ACCOUNT.Api,
							style: this.$api.CREDIT_ACCOUNT.Style,
							vmodel: "credit_account_id",
							subfield: "account_id",
							controller: "Accounts",
							enable: true,
						},
						{
							name: "ĐVT",
							field: "mainUnitId",
							width: "150px",
							type: TableDataStyle.TYPE.Combobox,
							pos: TableDataStyle.POS.Left,
							data: "units",
							vmodel: "mainUnitId",
							default: "main_unit_name",
							subfield: "unit_id",
							display: "unit_name",
							style: [
								{ name: "Tên đơn vị", field: "unit_name" },
								{ name: "Tỷ lệ chuyển đổi", field: "rate" },
							],
							enable: true,
						},
						{
							name: "Số lượng",
							field: "quantity",
							width: "150px",
							type: TableDataStyle.TYPE.Input,
							pos: TableDataStyle.POS.Right,
							enable: true,
						},
						{
							name: "Đơn giá",
							field: "debit_amount",
							width: "150px",
							type: TableDataStyle.TYPE.Input,
							pos: TableDataStyle.POS.Right,
							enable: true,
						},
						{
							name: "Thành tiền",
							field: "total_price",
							width: "100px",
							type: TableDataStyle.TYPE.Input,
							pos: TableDataStyle.POS.Right,
							enable: true,
						},
						{
							name: "Hạn sử dụng",
							field: "expiry",
							width: "150px",
							type: TableDataStyle.TYPE.InputDate,
							pos: TableDataStyle.POS.Left,
							enable: true,
						},
					],
					OBJECT: {
						name: "Đối tượng",
						field: "account_object_name",
						width: "150px",
						pos: TableDataStyle.POS.Left,
						api: this.$api.OBJECT.Api,
						style: this.$api.OBJECT.Style,
						vmodel: "accountobject_id",
						controller: "AccountObjects",
						form: 'showEmployeeForm',
						enable: true,
					},
					EMPLOYEE: {
						name: "Nhân viên",
						field: "employee_name",
						width: "150px",
						pos: TableDataStyle.POS.Left,
						api: this.$api.EMPLOYEE.Api,
						style: this.$api.EMPLOYEE.Style,
						vmodel: "employee_id",
						controller: "Employees",
						form: 'showEmployeeForm',
						enable: true,						
					}
				},
			},
		};
	},
};
